//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESCConstruct25.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Name]_[p1]x[p2]_[length]")]
        public string NameString {
            get {
                return ((string)(this["NameString"]));
            }
            set {
                this["NameString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rectangular@Rect|Circular@C|H Profile@H|L Profile@L|T Profile@T|U Profile@U")]
        public string TypeString {
            get {
                return ((string)(this["TypeString"]));
            }
            set {
                this["TypeString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double TableAnchorX {
            get {
                return ((double)(this["TableAnchorX"]));
            }
            set {
                this["TableAnchorX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double TableAnchorY {
            get {
                return ((double)(this["TableAnchorY"]));
            }
            set {
                this["TableAnchorY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BottomRightCorner")]
        public string TableLocationPoint {
            get {
                return ((string)(this["TableLocationPoint"]));
            }
            set {
                this["TableLocationPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatInExcel {
            get {
                return ((bool)(this["MatInExcel"]));
            }
            set {
                this["MatInExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatInBOM {
            get {
                return ((bool)(this["MatInBOM"]));
            }
            set {
                this["MatInBOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatInSTEP {
            get {
                return ((bool)(this["MatInSTEP"]));
            }
            set {
                this["MatInSTEP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string SerialNumber {
            get {
                return ((string)(this["SerialNumber"]));
            }
            set {
                this["SerialNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LicenseValid {
            get {
                return ((bool)(this["LicenseValid"]));
            }
            set {
                this["LicenseValid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN")]
        public string Construct_Language {
            get {
                return ((string)(this["Construct_Language"]));
            }
            set {
                this["Construct_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connectors\\ConnectorProperties.csv")]
        public string ConnectorProperties {
            get {
                return ((string)(this["ConnectorProperties"]));
            }
            set {
                this["ConnectorProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomProperty\\CompProperties.csv")]
        public string CompProperties {
            get {
                return ((string)(this["CompProperties"]));
            }
            set {
                this["CompProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fasteners\\Bolt.csv")]
        public string Bolt {
            get {
                return ((string)(this["Bolt"]));
            }
            set {
                this["Bolt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fasteners\\Nut.csv")]
        public string Nut {
            get {
                return ((string)(this["Nut"]));
            }
            set {
                this["Nut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fasteners\\Washer.csv")]
        public string Washer {
            get {
                return ((string)(this["Washer"]));
            }
            set {
                this["Washer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plates\\PlatesProperties.csv")]
        public string PlatesProperties {
            get {
                return ((string)(this["PlatesProperties"]));
            }
            set {
                this["PlatesProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_Circular.csv")]
        public string Profiles_Circular {
            get {
                return ((string)(this["Profiles_Circular"]));
            }
            set {
                this["Profiles_Circular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_H.csv")]
        public string Profiles_H {
            get {
                return ((string)(this["Profiles_H"]));
            }
            set {
                this["Profiles_H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_L.csv")]
        public string Profiles_L {
            get {
                return ((string)(this["Profiles_L"]));
            }
            set {
                this["Profiles_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_Rectangular.csv")]
        public string Profiles_Rectangular {
            get {
                return ((string)(this["Profiles_Rectangular"]));
            }
            set {
                this["Profiles_Rectangular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_T.csv")]
        public string Profiles_T {
            get {
                return ((string)(this["Profiles_T"]));
            }
            set {
                this["Profiles_T"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles\\Profiles_U.csv")]
        public string Profiles_U {
            get {
                return ((string)(this["Profiles_U"]));
            }
            set {
                this["Profiles_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserDXFProfiles\\profiles.csv")]
        public string profiles {
            get {
                return ((string)(this["profiles"]));
            }
            set {
                this["profiles"] = value;
            }
        }
    }
}
